#define DSBLOCK_VERSION_MAJOR @DSBLOCK_VERSION_MAJOR@
#define DSBLOCK_VERSION_MINOR @DSBLOCK_VERSION_MINOR@
#define DSBLOCK_VERSION_PATCH @DSBLOCK_VERSION_PATCH@
#define DSBLOCK_VERSION ((DSBLOCK_VERSION_MAJOR * 1000) + DSBLOCK_VERSION_MINOR) * 1000 + DSBLOCK_VERSION_PATCH
